
package vistas;

/**
 *
 * @author GPE
 */
public class DlgAyuda extends javax.swing.JDialog {

    /**
     * Creates new form DlgAyuda
     */
    public DlgAyuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblF3 = new javax.swing.JLabel();
        lblE2 = new javax.swing.JLabel();
        lblF6 = new javax.swing.JLabel();
        lblEnter2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblE = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblefectivo2 = new javax.swing.JLabel();
        lblC2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblF5 = new javax.swing.JLabel();
        lblF4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblF1 = new javax.swing.JLabel();
        lblF2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblE1 = new javax.swing.JLabel();
        lblT2 = new javax.swing.JLabel();
        lblModBascula = new javax.swing.JLabel();
        lblEnter = new javax.swing.JLabel();
        lblBuscar2 = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comandos de Ayuda");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Sylfaen", 2, 18)); // NOI18N
        lblTitulo.setText("Comandos de Acciones");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lblB.setForeground(new java.awt.Color(255, 0, 0));
        lblB.setText("Buscar Productos-");
        getContentPane().add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, -1));

        jLabel3.setText("Cancelacion Total");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lblF3.setForeground(new java.awt.Color(255, 0, 0));
        lblF3.setText("F3-");
        getContentPane().add(lblF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblE2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        lblE2.setText("Comandos:");
        getContentPane().add(lblE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lblF6.setForeground(new java.awt.Color(255, 0, 0));
        lblF6.setText("F6-");
        getContentPane().add(lblF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lblEnter2.setText("Código de barras + ENTER");
        getContentPane().add(lblEnter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel9.setText("Buscar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        lblE.setForeground(new java.awt.Color(255, 0, 0));
        lblE.setText("Cobrar en Efectivo-");
        getContentPane().add(lblE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

        lblX.setForeground(new java.awt.Color(255, 0, 0));
        lblX.setText("Modificar Bascula-");
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 110, -1));

        lblC.setForeground(new java.awt.Color(255, 0, 0));
        lblC.setText("Cobrar en Credito-");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 120, -1));

        lblefectivo2.setText("E+ ENTER");
        getContentPane().add(lblefectivo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        lblC2.setText("Cantidad + C - 400.50C");
        getContentPane().add(lblC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel15.setText("Cancelar Producto");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblF5.setForeground(new java.awt.Color(255, 0, 0));
        lblF5.setText("F5-");
        getContentPane().add(lblF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblF4.setForeground(new java.awt.Color(255, 0, 0));
        lblF4.setText("F4-");
        getContentPane().add(lblF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel18.setText("Menu Supervisor");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel19.setText("Ayuda");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        lblF1.setBackground(new java.awt.Color(255, 255, 255));
        lblF1.setForeground(new java.awt.Color(255, 0, 0));
        lblF1.setText("F1-");
        getContentPane().add(lblF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblF2.setForeground(new java.awt.Color(255, 0, 0));
        lblF2.setText("F2-");
        getContentPane().add(lblF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel22.setText("Cobrar");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        lblE1.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        lblE1.setText("Botones de Teclado:");
        getContentPane().add(lblE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblT2.setText("T+ ENTER");
        getContentPane().add(lblT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        lblModBascula.setText("Cantidad o peso + X: .250X");
        getContentPane().add(lblModBascula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        lblEnter.setForeground(new java.awt.Color(255, 0, 0));
        lblEnter.setText("Agregar Producto-");
        getContentPane().add(lblEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, -1));

        lblBuscar2.setText("B+ ENTER");
        getContentPane().add(lblBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        lblT.setForeground(new java.awt.Color(255, 0, 0));
        lblT.setText("Cobrar en Tarjeta-");
        getContentPane().add(lblT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoPV.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgAyuda dialog = new DlgAyuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblBuscar2;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblC2;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblE1;
    private javax.swing.JLabel lblE2;
    private javax.swing.JLabel lblEnter;
    private javax.swing.JLabel lblEnter2;
    private javax.swing.JLabel lblF1;
    private javax.swing.JLabel lblF2;
    private javax.swing.JLabel lblF3;
    private javax.swing.JLabel lblF4;
    private javax.swing.JLabel lblF5;
    private javax.swing.JLabel lblF6;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblModBascula;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblT2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblefectivo2;
    // End of variables declaration//GEN-END:variables
}
