package vistas;

import java.sql.SQLException;
import java.time.LocalTime;
import java.time.ZoneOffset;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.ControlClientes;
import negocio.ControlProductos;
import negocio.ControlVentas;
import objetosNegocio.Cliente;
import objetosNegocio.ProductoVenta;
import objetosNegocio.Venta;

/**
 *
 * @author Martin Bernal
 */
public class FrmReportesDeVenta extends javax.swing.JFrame {

    private ControlVentas controlVentas;
    private ControlProductos controlProductos;
    private ControlClientes controlClientes;

    /**
     * Creates new form FrmVentas
     */
    public FrmReportesDeVenta() {
        initComponents();
        this.controlClientes = new ControlClientes();
        this.controlVentas = new ControlVentas();
        this.dtpFechaHoraInicial.datePicker.setDateToToday();
        this.dtpFechaHoraInicial.timePicker.setTime(LocalTime.MIN);
        this.dtpFechaHoraFinal.datePicker.setDateToToday();
        this.dtpFechaHoraFinal.timePicker.setTime(LocalTime.MAX);
        try {
            this.cargarVentas();
        } catch (SQLException ex) {
            Logger.getLogger(FrmReportesDeVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.cargarClientesComboBox();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVentas = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblFechaInicial = new javax.swing.JLabel();
        dtpFechaHoraInicial = new com.github.lgooddatepicker.components.DateTimePicker();
        lblCliente = new javax.swing.JLabel();
        lblMontoFinal = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtMontoFinal = new javax.swing.JTextField();
        panVentas = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        cboxClientes = new javax.swing.JComboBox<>();
        lblFechaFinal = new javax.swing.JLabel();
        dtpFechaHoraFinal = new com.github.lgooddatepicker.components.DateTimePicker();
        lblDetallesDeVenta = new javax.swing.JLabel();
        lblCliente2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblProductos = new javax.swing.JLabel();
        panProductos = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes de Venta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVentas.setText("Buscador de ventas");
        lblVentas.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(0, 153, 51));
        getContentPane().add(lblVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 28, -1, -1));

        lblId.setText("ID:");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 46, -1, -1));

        lblFechaInicial.setText("Fecha y hora (Inicial):");
        getContentPane().add(lblFechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));
        getContentPane().add(dtpFechaHoraInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 119, 408, -1));

        lblCliente.setText("Cliente:");
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));

        lblMontoFinal.setText("Monto final:");
        getContentPane().add(lblMontoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        txtId.setEditable(false);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 43, 210, -1));

        txtMontoFinal.setEditable(false);
        txtMontoFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoFinalKeyTyped(evt);
            }
        });
        getContentPane().add(txtMontoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 210, -1));

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Fecha y hora", "Descuento", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblVentasMousePressed(evt);
            }
        });
        panVentas.setViewportView(tblVentas);

        getContentPane().add(panVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 237, 527, 220));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 201, -1, -1));

        cboxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        cboxClientes.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboxClientesPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cboxClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 81, 476, -1));

        lblFechaFinal.setText("Fecha y hora (Final):");
        getContentPane().add(lblFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, -1, -1));
        getContentPane().add(dtpFechaHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 407, -1));

        lblDetallesDeVenta.setText("Detalles de venta");
        getContentPane().add(lblDetallesDeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 11, -1, -1));

        lblCliente2.setText("Cliente:");
        getContentPane().add(lblCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 84, -1, -1));

        txtCliente.setEditable(false);
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 81, 210, -1));

        lblProductos.setText("Productos:");
        getContentPane().add(lblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo de  Barras", "Cantidad", "Nombre", "Precio", "Monto total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panProductos.setViewportView(tblProductos);

        getContentPane().add(panProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 187, 350, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoPantalla2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            this.cargarVentas();
        } catch (SQLException ex) {
            System.out.println("aqui");
            Logger.getLogger(FrmProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtMontoFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoFinalKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo puedes ingresar numeros.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtMontoFinalKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void cboxClientesPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboxClientesPopupMenuWillBecomeInvisible
        try {
            this.cargarVentas();
        } catch (SQLException ex) {
            Logger.getLogger(FrmReportesDeVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboxClientesPopupMenuWillBecomeInvisible

    private void tblVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentasMousePressed
        if (evt.getClickCount() >= 1) {
            this.limpiarFormulario();
            this.seleccionarVenta();
        }
    }//GEN-LAST:event_tblVentasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReportesDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReportesDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReportesDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReportesDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReportesDeVenta().setVisible(true);
            }
        });
    }

    public boolean verificacionDeCampos() {
        if (dtpFechaHoraInicial.getDatePicker().getText().equalsIgnoreCase("")
                || dtpFechaHoraFinal.getDatePicker().getText().equalsIgnoreCase("")) {
            return false;
        } else {
            return true;
        }
    }

    public void limpiarFormulario() {
        txtId.setText("");
        txtCliente.setText("");
        txtMontoFinal.setText("");
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0);
    }

    private void cargarVentas() throws SQLException {
      List<Venta> ventas = this.controlVentas.obtenerVentas(new Date(dtpFechaHoraInicial.getDateTimeStrict().toEpochSecond(ZoneOffset.UTC)),
                new Date(dtpFechaHoraFinal.getDateTimeStrict().toEpochSecond(ZoneOffset.UTC)),
                (cboxClientes.getSelectedIndex() == 0) ? null : (Cliente) cboxClientes.getSelectedItem());

        if (ventas != null) {
            DefaultTableModel modelo
                    = (DefaultTableModel) tblVentas.getModel();
            modelo.setRowCount(0);
            for (Venta venta : ventas) {
                modelo.addRow(venta.toArray());
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron ventas en esas fechas :(", "Error Vistas", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void seleccionarVenta() {
        Integer fila = tblVentas.getSelectedRow();
        DefaultTableModel modeloProductos = (DefaultTableModel) tblProductos.getModel();
        DefaultTableModel modeloVentas = (DefaultTableModel) tblVentas.getModel();
        ProductoVenta productos = new ProductoVenta();

        Integer idVenta = (Integer) modeloVentas.getValueAt(fila, 0);
        Venta venta;
        try {
            venta = controlVentas.obtenerVentaPorId(idVenta);

            txtId.setText(String.valueOf(venta.getId()));
            if(venta.getCliente()!=null){
            txtCliente.setText(venta.getCliente().getNombre()+"");
            }
            txtMontoFinal.setText(String.valueOf(venta.getTotal()));
            Float subtotal = 0F;
            for (ProductoVenta producto : venta.getProductos()) {
                modeloProductos.addRow(producto.toArray());
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmReportesDeVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarClientesComboBox() {
        List<Cliente> clientes = this.controlClientes.obtenerClientesComboBox();
        if (clientes != null) {
            cboxClientes.removeAllItems();
            cboxClientes.addItem("Todos");
            for (Cliente cliente : clientes) {
                cboxClientes.addItem(cliente);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<Object> cboxClientes;
    private com.github.lgooddatepicker.components.DateTimePicker dtpFechaHoraFinal;
    private com.github.lgooddatepicker.components.DateTimePicker dtpFechaHoraInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCliente2;
    private javax.swing.JLabel lblDetallesDeVenta;
    private javax.swing.JLabel lblFechaFinal;
    private javax.swing.JLabel lblFechaInicial;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMontoFinal;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JScrollPane panProductos;
    private javax.swing.JScrollPane panVentas;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMontoFinal;
    // End of variables declaration//GEN-END:variables
}
